[package]
name = "vr8-core"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "2.2.0", features = [] }
hound = "3.5.1"
rayon = "1.10.0"
indicatif = "0.17.9"
serde = { version = "1", features = ["derive"] }
