[package]
name = "vr8-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
vr8-core = { path = "../vr8-core" }
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.42.0", features = ["full"] }
